---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
spec:
  values:
    nfs:
      server: 192.168.1.101
      path: /volume1/k8s
      mountOptions:
      - vers=4.1
    storageClass:
      defaultClass: true
      name: synology
