---
- name: install system packages
  apt:
    name: "{{ main_packages }}"
    state: present
    cache_valid_time: 3600

- name: Upgrade the system
  apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    cache_valid_time: 3600
  when: upgrade == True
