---
- name: Install Apt Mirror
  block:
    - name: Remove old sources.list
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "/etc/apt/sources.list"
        - "/etc/apt/sources.list~"

    - name: Install Main Repo
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items:
        - "deb http://deb.debian.org/debian {{debian_release}} main contrib non-free"
        - "deb http://deb.debian.org/debian {{debian_release}}-updates main contrib non-free"
        - "deb http://deb.debian.org/debian {{debian_release}}-backports main contrib non-free"
        - "deb http://security.debian.org/debian-security {{debian_release}}-security main contrib non-free"

- name: install system packages
  apt:
    name: "{{ main_packages }}"
    state: present
    cache_valid_time: 3600

- name: Upgrade the system
  apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    cache_valid_time: 3600
  when: upgrade == True
