---
- name: Install Log2ram
  block:
    - name: Install Log2ram Repo
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items:
        - "deb http://packages.azlux.fr/debian/ {{debian_release}} main"
    - name: install Log2ram package
      apt:
        name: "log2ram"
        state: present
        cache_valid_time: 3600
    - name: Configure Log2ram
      copy:
        src: "log2ram.conf"
        dest: "/etc/log2ram.conf"
        mode: "0644"

- meta: flush_handlers
- name: Check provisioned file
  stat:
    path: "/provisioned"
  register: st_provision

- name: Configure motd
  block:
    - name: Create motd
      command: figlet "{{ ansible_hostname }}"
      register: motd

    - name: Save motd
      copy:
        dest: "/etc/motd"
        mode: "0644"
        content: "{{ motd.stdout }}"
  when: st_provision.stat.exists == False

- name: Reboot system after provisioned
  reboot:
  when: st_provision.stat.exists == False

- name: Create provisioned file
  file:
    path: "/provisioned"
    state: touch
    mode: "0400"
  when: st_provision.stat.exists == False

